### PR TITLE
attempt Windows build with clang

### PR DESCRIPTION
**Pull request by danielnachun**
The purpose of this PR is to try to build `r-sf` with Clang on Windows.  Unlike MinGW, Clang can use the MSVC C++ standard library, which matches the standard library use for `proj`, `geos` and `libgdal`, which should avoid errors that arise from mismatching C++ libraries.

### CODE REVIEW

**Comment by danielnachun** [comment]
@ocefpaf @mfansler It looks like the switch over to `r_clang` plus a bit of patching was sufficient to get this working on Windows!  Please take a look and let me know if you want any further changes.

**Review by ocefpaf — APPROVED** [review]
LGTM. Thanks! I wonder if we should try that approach in other places that have similar failures.

**Comment by danielnachun** [comment]
Indeed, this was inspired the idea in https://github.com/conda-forge/r-terra-feedstock/pull/97, and I'm trying to move `r-terra` forward in this PR: https://github.com/conda-forge/r-terra-feedstock/pull/102.  I was also thinking it might be needed for `xgboost`, but there seems to be progress there now.

In general I believe the `r_clang` package is the best way to build Rcpp packages that need to link to external C++ libraries that are linked to the MSVC C++ standard library.  MinGW doesn't seem to have any way to link to MSVC C++, while Clang has long supported this.

**Comment by mfansler** [comment]
Nice work!! 🚀

**Pull request merged**
